stages:
  load_data:
    cmd: python src/load_data.py
    deps:
    - src/load_data.py
    - data/raw/water_potability.csv

  split_data:
    cmd: python src/split_data.py
    deps:
    - src/split_data.py
    - data/raw/water_potability.csv
    outs:
    - data/processed/train_waterq.csv
    - data/processed/test_waterq.csv

  feature_scaling:
    cmd: python src/feature_scaling.py
    deps:
    - src/feature_scaling.py
    - data/processed/train_waterq.csv
    - data/processed/test_waterq.csv
